# https://docs.docker.com/compose/compose-file
version: '3'

services:
  redis:
    image: "redis:alpine"
    hostname: redis
    networks:
      - redis-net
    volumes:
      - redis-data:/data
    ports: 
      - 6379:6379
  app:
    build: .
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - POLKADOT_HOST=wss://poc3-rpc.polkadot.io
    networks:
      - redis-net
    volumes:
      - ./:/var/www/app
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development

networks:
  redis-net:

volumes:
  redis-data:
